### ISSUE TITLE
MyPlot Plugin

### ISSUE THREAD

**Issue by xXRyzen** [GenisysProPlugins/PluginRequests#12]
Works with PMMP: 
Yes

Issue: 
[Server thread/CRITICAL]: ClassNotFoundException: "Class spoondetector\SpoonDetector not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Link to Git Repo:
https://github.com/jasonwynn10/MyPlot

**Comment by andris155** [comment]
Use poggit build: https://poggit.pmmp.io/ci/jasonwynn10/MyPlot/MyPlot

**Comment by MasterOfTheRealm** [comment]
Sorry guys away on vacation. i'll get everything done when i get back.

**Comment by xXRyzen** [comment]
@andris155 Crashes server with following error:

Error: Declaration of MyPlot\MyPlotGenerator::generateChunk(int $chunkX, int $chunkZ) must be compatible with pocketmine\level\generator\Generator::generateChunk($chunkX, $chunkZ)
File: /MyPlot.phar/src/MyPlot/MyPlotGenerator
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : MyPlot v1.1.6

Code:
[1] <?php
[2] namespace MyPlot;
[3] 
[4] use pocketmine\block\Block;
[5] use pocketmine\level\generator\Generator;
[6] use pocketmine\level\ChunkManager;
[7] use pocketmine\math\Vector3;
[8] use pocketmine\utils\Random;
[9] use pocketmine\level\Level;
[10]
