### ISSUE TITLE
Slapper Plugin

### ISSUE THREAD

**Issue by xXRyzen** [GenisysProPlugins/PluginRequests#13]
Works with PMMP:
Yes

Issue:
[Server thread/CRITICAL]: Unhandled exception executing command 'slapper add fallingsand TESTING' in slapper: Class pocketmine\network\mcpe\protocol\AddEntityPacket not found
2017-08-10 [19:09:36] 
[Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Link to Git Repo:
https://github.com/jojoe77777/Slapper

**Comment by DerddyDert** [comment]
\mcpe\ don't exist

**Comment by Saxavlax001** [comment]
https://github.com/GenisysProPlugins/Slapper
