### ISSUE TITLE
Dracula - LifeSteal

### ISSUE THREAD

**Issue by nasiridrishi** [GenisysProPlugins/PluginRequests#6]
dawnload link :- https://imgcl.co/plugins/dracula-lifesteal.733/
       Error in GenisysPro:- Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'Dracula-LifeSteal v2': Trying to get permissions of closed player on Az928\Dracula\Main
       [15:27:43] [Server thread/CRITICAL]: InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 686

**Comment by DerddyDert** [comment]
I need this one too. @MasterOfTheRealm

**Comment by ghost** [comment]
Can u add a feature to it:
 we can specify how many hearts u regen per hit .

**Comment by TheAz928** [comment]
This was my plugin, but no one reported me even a single bug? *face palm* I'll fix this...

**Comment by ghost** [comment]
@TheAz928 maybe because u didn't add that plugin to ur github account?

**Comment by TheAz928** [comment]
Yeah, I totally forgot...

**Comment by TheAz928** [comment]
Anyway, visit @ShiningMC for my latest plugins lol
@mote166 @DerddyDert@MasterOfTheRealm

**Comment by DerddyDert** [comment]
@TheAz928 awesome

**Comment by MasterOfTheRealm** [comment]
Nice!
