### ISSUE TITLE
Could not protect Items in the frame.

### ISSUE THREAD

**Issue by TeddyPE** [GenisysProPlugins/PluginRequests#8]
Issue description
I can't protect Items in the frame.
The protection plugin could not protect it.
Even when I installed spawn-protection, things were broken.

How can I solve it?

**Comment by DerddyDert** [comment]
Spawn-Protection does not cover items in item frames. World/area protection plugus i.e., World Protect, WorldGuard, and iProtector also do not cover items in item frames. Provide a link to a finished item frame protector plugin that needs to be updated to work on genisyspro or create one.

**Comment by MasterOfTheRealm** [comment]
There is a version of Iprotector that protects itemframes as well

**Comment by MasterOfTheRealm** [comment]
https://github.com/kenygamer/iProtector-v4.0

try this and tell me if it works

**Comment by EinBexiii** [comment]
Use the ItemFrameDropItemEvent.
If you want the items do not move in the ItemFrame use the PlayerInteract Event.

**Comment by TeddyPE** [comment]
@MasterOfTheRealm I solved it! Thank you. :)
